# Generated by Django 4.0.4 on 2022-06-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cpu'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gpu'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ram'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.screensize'),
        ),
    ]
